apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3d-cluster
image: rancher/k3s:v1.34.1-k3s1
servers: 1
agents: 2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
  - port: 30432:30432
    nodeFilters:
      - loadbalancer
volumes:
  - volume: /home/dsm/cluster:/mnt/cluster
    nodeFilters:
      - all
