apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
  namespace: n8n
spec:
  secretName: n8n-tls
  issuerRef:
    name: k3d-selfsigned
    kind: ClusterIssuer
  dnsNames:
    - n8n.local.127.0.0.1.nip.io
