# Prometheus PVCs - Persistent Volume Claims
# Define COMO as aplicações solicitam armazenamento
# Vincula-se aos PVs através dos seletores (labels)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: prometheus
  labels:
    app: prometheus
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-storage
  selector:
    matchLabels:
      app: prometheus
      component: storage
      storage-type: hostpath
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-config-pvc
  namespace: prometheus
  labels:
    app: prometheus
    component: config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-storage
  selector:
    matchLabels:
      app: prometheus
      component: config
      storage-type: hostpath
  resources:
    requests:
      storage: 1Gi
