apiVersion: v1
kind: Secret
metadata:
  name: prometheus-db-secret
  namespace: prometheus
type: Opaque
stringData:
  # PostgreSQL Database Configuration
  DB_POSTGRESDB_HOST: postgres.postgres.svc.cluster.local
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: prometheus
  DB_POSTGRESDB_USER: postgres
  DB_POSTGRESDB_PASSWORD: postgres_admin

  # Redis Cache Configuration
  REDIS_HOST: redis.redis.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD: Redis_Shared_Cache_K8s_2024_9105092354952d9a
  REDIS_DB: "3"
