apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: grafana
spec:
  secretName: grafana-tls
  issuerRef:
    name: k3d-selfsigned
    kind: ClusterIssuer
  dnsNames:
    - grafana.local.127.0.0.1.nip.io
