# Grafana PVCs - Persistent Volume Claims
# Define COMO as aplicações solicitam armazenamento
# Vincula-se aos PVs através dos seletores (labels)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
  labels:
    app: grafana
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-storage
  selector:
    matchLabels:
      app: grafana
      component: storage
      storage-type: hostpath
  resources:
    requests:
      storage: 10Gi
---
# PVC adicional para dados de dashboard e plugins
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: grafana
  labels:
    app: grafana
    component: data-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-storage
  selector:
    matchLabels:
      app: grafana
      component: data-storage
      storage-type: hostpath
  resources:
    requests:
      storage: 5Gi
